wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1634581135
    t:
      1:
      - 5
      - 12
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.4
      8:
      - 1
      - 2
      - 5
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: mendeley
random_seed:
  desc: null
  value: 12
resolution:
  desc: null
  value: 256
